name: CI/CD

# only on trunk branch use secrets
on:
  workflow_dispatch:
    inputs:
      aws-account-name:
        description: "AWS Account Name"
        required: true
        type: string
      common-name:
        description: "The name used acrross many resources, usually account-region-project-repo-branch"
        required: true
        type: string
      backend-dns:
        description: "The adress of the backend, e.g. http://localhost:8080"
        required: true
        type: string
      task-desired-count:
        description: "The number of tasks to run in the service"
        required: true
        type: string

env:
  AWS_ACCOUNT_NAME: ${{ inputs.aws-account-name }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  COMMON_NAME: ${{ inputs.common-name }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.8.0
      - run: npm ci
      - run: npm run build

  s3-env:
    name: S3 env
    runs-on: ubuntu-latest
    environment: ${{ inputs.aws-account-name }}
    env:
      BACKEND_DNS: ${{ inputs. backend-dns }}
      BRANCH: ${{ github.head_ref || github.ref_name }}
      AWS_ACCESS_KEY_ENV: ${{ secrets.AWS_ACCESS_KEY }}
      BUCKET_ENV: ${{ inputs.common-name }}-env

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup
        id: setup
        run: |
          apt update -qq
          apt install wget -y -qq
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64  -qq -O /usr/bin/yq
          chmod +x /usr/bin/yq
          echo "PORT=$(yq eval '.port' config/config.yml)" >> $GITHUB_OUTPUT

      - name: Display
        run: |
          printf " \
          AWS_ACCOUNT_NAME = $AWS_ACCOUNT_NAME\n \
          BRANCH = $BRANCH\n \
          AWS_REGION = $AWS_REGION\n \
          AWS_ACCESS_KEY = ${{ secrets.AWS_ACCESS_KEY }}\n \
          AWS_SECRET_KEY = ${{ secrets.AWS_SECRET_KEY }}\n \
          S3 file = s3://$BUCKET_ENV/$BRANCH.env\n \
          "

      - name: setup AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region $AWS_REGION

      - name: Upload env file
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_API_URL=$BACKEND_DNS
          PORT=${{ steps.setup.outputs.PORT }}
          EOF
          aws s3 cp .env s3://$BUCKET_ENV/$BRANCH.env

  ecr:
    name: ECR
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.aws-account-name }}
    env:
      AWS_CLI_SERVICE: ecr
      DOCKER_FOLDER_PATH: Dockerfile
      ECR_REPOSITORY: ${{ inputs.common-name }}
      IMAGE_TAG: "latest"
    needs: [build]
    outputs:
      IMAGE_TAG: ${{ steps.build-image.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Display non-sensitive variables
        run: |
          printf " \
          AWS_CLI_SERVICE = $AWS_CLI_SERVICE\n \
          AWS_ACCOUNT_ID = $AWS_ACCOUNT_ID\n \
          AWS_REGION = $AWS_REGION\n \
          ECR_REPOSITORY = $ECR_REPOSITORY\n \
          "

      - name: setup AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region $AWS_REGION

      - name: Get ECR login password
        id: get-login-password
        run: |
          if [[ $AWS_CLI_SERVICE == ecr ]]; then
            echo "ECR_LOGIN_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT
          elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
            echo "ECR_LOGIN_PASSWORD=$(aws ecr-public get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT  | docker login --username AWS --password-stdin public.ecr.aws
          fi

      - name: login to ECR
        run: |
          if [[ $AWS_CLI_SERVICE == ecr ]]; then
            docker login --username AWS --password ${{ steps.get-login-password.outputs.ECR_LOGIN_PASSWORD }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
            docker login --username AWS --password ${{ steps.get-login-password.outputs.ECR_LOGIN_PASSWORD }} public.ecr.aws
          fi

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          export ECR_URI=$(aws $AWS_CLI_SERVICE describe-repositories --repository-names $ECR_REPOSITORY --output text --query "repositories[].[repositoryUri]")
          echo "ECR_URI= $ECR_URI"
          # docker build ${GITHUB_WORKSPACE}/$DOCKER_FOLDER_PATH -t $ECR_URI/$IMAGE_TAG
          docker build -t $ECR_URI/$IMAGE_TAG -f $DOCKER_FOLDER_PATH .
          docker tag $(docker images -q $ECR_URI/$IMAGE_TAG) $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
      
      - name: Wait for image to be available
        run: |
          aws ecr wait image-scan-complete --repository-name $ECR_REPOSITORY --image-id imageTag=$IMAGE_TAG
          aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG --output json

  ecs:
    name: ECS
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.aws-account-name }}
    needs: [ecr, s3-env]
    env:
      IMAGE_TAG: ${{ needs.ecr.outputs.IMAGE_TAG }}
      DESIRED_COUNT: ${{ inputs.task-desired-count }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Display variables
        run: |
          printf " \
          AWS_REGION = $AWS_REGION\n \
          IMAGE_TAG = $IMAGE_TAG\n \
          "

      - name: setup AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region $AWS_REGION

      - name: Update service
        run: |
          LATEST_TASK_ARN=$(aws ecs list-task-definitions \
            --region $AWS_REGION \
            --family-prefix $COMMON_NAME \
            --sort DESC \
            --query 'taskDefinitionArns[0]' \
            --output text)
          aws ecs update-service \
            --cluster $COMMON_NAME \
            --service $COMMON_NAME \
            --force-new-deployment \
            --region $AWS_REGION \
            --task-definition $LATEST_TASK_ARN \
            --desired-count $DESIRED_COUNT \
            --output json

      - name: Wait for tasks
        run: |
          sleep 30s
          TASKS=$(aws ecs list-tasks \
          --region $AWS_REGION \
          --cluster $COMMON_NAME \
          --query 'taskArns[]' \
          --output text)
          echo $TASKS
          LATEST_TASK_DEFINITION_ARN=$(aws ecs list-task-definitions \
          --region $AWS_REGION \
          --family-prefix $COMMON_NAME \
          --sort DESC \
          --query 'taskDefinitionArns[0]' \
          --output text)

          for task in $TASKS; do
              tasksDescription=$(aws ecs describe-tasks --region $AWS_REGION --cluster $COMMON_NAME --tasks $task --query 'tasks[]' --output json) || exit 1
              echo "tasksDescription=$tasksDescription"
              latestStatus=$(jq -r  '.[]|.lastStatus' <<< $tasksDescription)
              taskDefinitionArn=$(jq -r  '.[]|.taskDefinitionArn' <<< $tasksDescription)
              echo "Waiting for task $task to be RUNNING, currently $latestStatus"
              echo "Waiting for task $task to have definition ARN $LATEST_TASK_DEFINITION_ARN, currently $taskDefinitionArn"
              
              i=0
              while [[ $latestStatus != "RUNNING" && taskDefinitionArn != $LATEST_TASK_DEFINITION_ARN ]]; do
                tasksDescription=$(aws ecs describe-tasks --region $AWS_REGION --cluster $COMMON_NAME --tasks $task --query 'tasks[]' --output json)
                latestStatus=$(jq -r  '.[]|.lastStatus' <<< $tasksDescription)
                taskDefinitionArn=$(jq -r  '.[]|.taskDefinitionArn' <<< $tasksDescription)
                echo "Waiting for task $task to be RUNNING, currently $latestStatus"
                echo "Waiting for task $task to have definition ARN $LATEST_TASK_DEFINITION_ARN, currently $taskDefinitionArn"
                sleep 10s

                if [ $i -gt 30 ] || [ "$latestStatus" = "STOPPED" ]; then exit 1; fi
                i=$((i+1))
              done
          done