name: Test container

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test-container:
    name: Build dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: |-
          docker build \
            --tag "tests:$GITHUB_SHA" \
            . \
            -f Dockerfile